import { NestFactory } from '@nestjs/core';
import { AppModule } from '../app.module';
import { ProductsService } from '../modules/products/products.service';
import { getArgNumber, randInt } from './seed-utils';

async function main() {
  const count = getArgNumber('count', 100);
  const start = getArgNumber('start', Date.now());

  const app = await NestFactory.createApplicationContext(AppModule, {
    logger: ['log', 'warn', 'error'],
  });

  try {
    const productsService = app.get(ProductsService);

    let created = 0;
    for (let i = 0; i < count; i++) {
      const sku = `SKU-${start}-${i}`;
      const name = `Seed Product ${i + 1}`;
      const stock = randInt(0, 200);
      const price = Number((randInt(100, 50000) / 100).toFixed(2));

      await productsService.create({
        sku,
        name,
        description: `Seeded product generated by script (${sku})`,
        stock,
        price,
      });

      created++;
      if (created % 25 === 0) console.log(`Created ${created}/${count} products...`);
    }

    console.log(`Done. Created ${created} products.`);
  } finally {
    await app.close();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
